/**
 * TwinCAT XML source extractor.
 *
 * Extracts Structured Text (ST) source code from TwinCAT 3 XML file formats:
 *   .TcPOU  – Function blocks, programs, functions (Declaration + Implementation)
 *   .TcGVL  – Global variable lists (Declaration only)
 *   .TcDUT  – Data unit types / type definitions (Declaration only)
 *   .TcIO   – Interfaces (.TcIO) (Declaration only)
 *   .st     – Plain ST files (pass-through, no extraction)
 *
 * For each extracted file the module builds a line-number map so that the LSP
 * can translate positions in the *extracted* source back to positions in the
 * *original* XML file for diagnostics, hover info, etc.
 */

import * as path from 'path';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface ExtractedSection {
  /** Whether this section holds declarations, executable code, or an action body. */
  kind: 'declaration' | 'implementation' | 'action';
  /** The raw ST text from this section (no surrounding XML). */
  content: string;
  /**
   * 0-based line in the *original* file where this section's first content
   * line begins.
   */
  startLine: number;
  /**
   * 0-based character offset within `startLine` where this section's content
   * begins. This is 0 when the CDATA opens on its own line, or > 0 when the
   * ST content starts on the same line as `<![CDATA[`.
   */
  startChar: number;
  /** Action name — only present when kind === 'action'. */
  actionName?: string;
}

// ---------------------------------------------------------------------------
// XmlRange — matches the shape of vscode-languageserver-types Range
// ---------------------------------------------------------------------------

/** A character-level range in an XML source file (0-based line/character). */
export interface XmlRange {
  start: { line: number; character: number };
  end: { line: number; character: number };
}

export interface ExtractionResult {
  /**
   * Combined ST source ready for the lexer/parser.
   * For files that have both a Declaration and an Implementation the two are
   * joined with a single newline.
   */
  source: string;
  /**
   * Maps each 0-based line index in `source` to the corresponding 0-based
   * line index in the original file.
   *
   * lineMap[n] = original file line for extracted line n
   */
  lineMap: number[];
  /** Individual sections in the order they were extracted. */
  sections: ExtractedSection[];
  /**
   * True when the file was treated as plain ST with no XML extraction.
   * In this case source === original content and lineMap[n] === n.
   */
  passthrough: boolean;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

const CDATA_OPEN = '<![CDATA[';
const CDATA_OPEN_LEN = CDATA_OPEN.length; // 9
const CDATA_CLOSE = ']]>';

/** Return the 0-based line number at character position `pos` in `str`. */
function lineAtPos(str: string, pos: number): number {
  let line = 0;
  for (let i = 0; i < pos; i++) {
    if (str[i] === '\n') line++;
  }
  return line;
}

interface RawCData {
  content: string;
  kind: 'declaration' | 'implementation' | 'action';
  /** 0-based line in the original file where the first line of content lives. */
  startLine: number;
  /** 0-based character offset within startLine where content begins. */
  startChar: number;
  /** For action sections: the name from the <Action Name="..."> attribute. */
  actionName?: string;
  /** For action sections: line of the synthetic ACTION header in the original file. */
  headerLine?: number;
}

/**
 * Find the first top-level Declaration CDATA and the first Implementation/ST
 * CDATA within `xml`.
 *
 * We intentionally ignore nested CDATAs (e.g., inside <Method> children) and
 * only capture the POU/GVL/DUT/Itf top-level sections.  The strategy is:
 *
 *  1. Find the outermost element tag (<POU>, <GVL>, <DUT>, <Itf>).
 *  2. Within that element, find the first <Declaration> and the first
 *     <Implementation> (which wraps a <ST> element).
 *
 * Because the XML is machine-generated by TwinCAT we can rely on its
 * predictable structure and use regex matching instead of a full XML parser.
 */
function extractTopLevelCDATAs(xml: string): RawCData[] {
  const results: RawCData[] = [];

  // Find the top-level container element: <POU…>, <GVL…>, <DUT…>, or <Itf…>.
  // We look for the opening tag and capture from its position.
  const containerRe = /<(POU|GVL|DUT|Itf)\b[^>]*>/i;
  const containerMatch = containerRe.exec(xml);
  if (!containerMatch) return results;

  const containerStart = containerMatch.index;
  const containerTagName = containerMatch[1];

  // Find the closing tag for this container element.
  const closingTag = `</${containerTagName}>`;
  const containerEnd = xml.indexOf(closingTag, containerStart);
  const body = containerEnd === -1
    ? xml.slice(containerStart)
    : xml.slice(containerStart, containerEnd + closingTag.length);

  // Within the container body, find the first <Declaration> (direct child).
  // We stop before any nested child element that also has a <Declaration>.
  const declResult = extractFirstChildCData(xml, body, containerStart, 'Declaration', 'declaration');
  if (declResult) results.push(declResult);

  // Find Implementation > ST CDATA.
  const implResult = extractImplementationCData(xml, body, containerStart);
  if (implResult) results.push(implResult);

  // For POU containers, also extract <Action Name="..."> children.
  if (containerTagName.toUpperCase() === 'POU') {
    const actionResults = extractActionCDATAs(xml, body, containerStart);
    results.push(...actionResults);
  }

  return results;
}

/**
 * Extract the CDATA content from the first direct-child `<tagName>` element
 * within `body`.  `bodyOffsetInXml` is the character offset of `body` within
 * the full `xml` string (used for accurate line counting).
 */
function extractFirstChildCData(
  xml: string,
  body: string,
  bodyOffsetInXml: number,
  tagName: string,
  kind: 'declaration' | 'implementation',
): RawCData | null {
  // Match the first occurrence of <tagName(…)>…</tagName>
  const tagRe = new RegExp(`<${tagName}\\b[^>]*>([\\s\\S]*?)<\\/${tagName}>`, 'i');
  const m = tagRe.exec(body);
  if (!m) return null;

  const innerContent = m[1];
  const cdataIdx = innerContent.indexOf(CDATA_OPEN);
  if (cdataIdx === -1) return null;

  const cdataCloseIdx = innerContent.indexOf(CDATA_CLOSE, cdataIdx + CDATA_OPEN_LEN);
  if (cdataCloseIdx === -1) return null; // malformed – CDATA not closed

  // Raw content between <![CDATA[ and ]]>
  let raw = innerContent.slice(cdataIdx + CDATA_OPEN_LEN, cdataCloseIdx);

  // Position of the first character *after* <![CDATA[ in the full xml string.
  const contentPosInXml =
    bodyOffsetInXml +
    m.index +
    m[0].indexOf(CDATA_OPEN) +
    CDATA_OPEN_LEN;

  // Determine startLine: if the character right after <![CDATA[ is a newline
  // the content begins on the following line.
  let startLine = lineAtPos(xml, contentPosInXml);

  // Determine startChar: walk backwards from contentPosInXml to find the line start.
  let lineStartPos = contentPosInXml;
  while (lineStartPos > 0 && xml[lineStartPos - 1] !== '\n') lineStartPos--;
  let startChar = contentPosInXml - lineStartPos;

  if (raw.startsWith('\n')) {
    startLine += 1;
    raw = raw.slice(1); // strip leading newline
    startChar = 0;      // content now begins at start of the next line
  }

  // Strip a single trailing newline (TwinCAT often writes `…\n]]>`)
  if (raw.endsWith('\n')) {
    raw = raw.slice(0, -1);
  }

  return { content: raw, kind, startLine, startChar };
}

/**
 * Extract the CDATA content from `<Implementation><ST><![CDATA[…]]></ST></Implementation>`.
 */
function extractImplementationCData(
  xml: string,
  body: string,
  bodyOffsetInXml: number,
): RawCData | null {
  // Find the first <Implementation> block in body.
  const implRe = /<Implementation\b[^>]*>([\s\S]*?)<\/Implementation>/i;
  const implMatch = implRe.exec(body);
  if (!implMatch) return null;

  const implInner = implMatch[1];
  const implOffsetInXml = bodyOffsetInXml + implMatch.index;

  // Within Implementation, find <ST>…</ST>
  return extractFirstChildCData(xml, implInner, implOffsetInXml, 'ST', 'implementation');
}

/**
 * Extract all <Action Name="..."> implementation CDATAs from a POU body.
 * Each action has only an <Implementation><ST> section (no <Declaration>).
 */
function extractActionCDATAs(
  xml: string,
  body: string,
  bodyOffsetInXml: number,
): RawCData[] {
  const results: RawCData[] = [];

  // Match all <Action ... Name="ActionName" ...> opening tags in the body.
  const actionTagRe = /<Action\b([^>]*)>/gi;
  let tagMatch: RegExpExecArray | null;

  while ((tagMatch = actionTagRe.exec(body)) !== null) {
    const attrStr = tagMatch[1];
    const nameMatch = /\bName="([^"]+)"/i.exec(attrStr);
    if (!nameMatch) continue;

    const actionName = nameMatch[1];
    const actionTagPosInXml = bodyOffsetInXml + tagMatch.index;
    const headerLine = lineAtPos(xml, actionTagPosInXml);

    // Find the content between <Action ...> and </Action>.
    const actionBodyStart = tagMatch.index + tagMatch[0].length;
    const actionCloseTag = '</Action>';
    const actionCloseIdx = body.indexOf(actionCloseTag, actionBodyStart);
    const actionBodyText = actionCloseIdx === -1
      ? body.slice(actionBodyStart)
      : body.slice(actionBodyStart, actionCloseIdx);

    // Extract Implementation > ST CDATA from the action body.
    const implCData = extractImplementationCData(
      xml,
      actionBodyText,
      bodyOffsetInXml + actionBodyStart,
    );
    if (!implCData) continue;

    results.push({
      ...implCData,
      kind: 'action',
      actionName,
      headerLine,
    });
  }

  return results;
}

/**
 * Build an ExtractionResult from a list of ordered raw CDATA sections.
 */
function buildResult(cdatas: RawCData[]): ExtractionResult {
  if (cdatas.length === 0) {
    return { source: '', lineMap: [], sections: [], passthrough: false };
  }

  const sections: ExtractedSection[] = cdatas.map((c) => ({
    kind: c.kind,
    content: c.content,
    startLine: c.startLine,
    startChar: c.startChar,
    actionName: c.actionName,
  }));

  const sourceParts: string[] = [];
  const lineMap: number[] = [];

  for (let si = 0; si < cdatas.length; si++) {
    const c = cdatas[si];

    // Add a blank separator line between sections (mapped to the line
    // immediately before the next section's content begins in the original).
    if (si > 0) {
      const separatorLine = c.startLine > 0 ? c.startLine - 1 : c.startLine;
      lineMap.push(separatorLine);
      sourceParts.push('');
    }

    if (c.kind === 'action') {
      // Wrap action body with synthetic ACTION <name>: / END_ACTION header+footer.
      const hdrLine = c.headerLine ?? (c.startLine > 0 ? c.startLine - 1 : c.startLine);
      // ACTION <name>: header line
      lineMap.push(hdrLine);
      sourceParts.push(`ACTION ${c.actionName}:`);

      const lines = c.content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        lineMap.push(c.startLine + i);
      }
      sourceParts.push(c.content);

      // END_ACTION footer line (mapped just past the last content line)
      lineMap.push(c.startLine + lines.length);
      sourceParts.push('END_ACTION');
    } else {
      const lines = c.content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        lineMap.push(c.startLine + i);
      }
      sourceParts.push(c.content);
    }
  }

  return {
    source: sourceParts.join('\n'),
    lineMap,
    sections,
    passthrough: false,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * File extensions that require XML extraction.
 * All comparisons are done case-insensitively.
 */
const XML_EXTENSIONS = new Set(['.tcpou', '.tcgvl', '.tcdut', '.tcio', '.tctask']);

/**
 * Return all character-level ranges in `text` that lie *outside* CDATA
 * section content.  These ranges cover the XML wrapper (including the
 * `<![CDATA[` and `]]>` markers themselves).
 *
 * Each XmlRange uses 0-based line/character positions compatible with the
 * vscode-languageserver-types `Range` interface.
 *
 * Callers should only invoke this for files whose extension is in
 * `XML_EXTENSIONS`.
 */
export function getXmlRanges(text: string): XmlRange[] {
  const result: XmlRange[] = [];

  /** Convert a character offset in `text` to a {line, character} position. */
  function posToLocation(offset: number): { line: number; character: number } {
    let line = 0;
    let lineStart = 0;
    for (let i = 0; i < offset; i++) {
      if (text[i] === '\n') {
        line++;
        lineStart = i + 1;
      }
    }
    return { line, character: offset - lineStart };
  }

  let xmlStart = 0; // start (inclusive) of the current XML wrapper region
  let pos = 0;

  while (pos < text.length) {
    const cdataOpen = text.indexOf(CDATA_OPEN, pos);
    if (cdataOpen === -1) break;

    const cdataContentStart = cdataOpen + CDATA_OPEN_LEN; // first char of CDATA content
    const cdataClose = text.indexOf(CDATA_CLOSE, cdataContentStart);
    if (cdataClose === -1) break; // malformed

    // XML wrapper region: from xmlStart up to (and including) '<![CDATA['
    if (cdataContentStart > xmlStart) {
      result.push({ start: posToLocation(xmlStart), end: posToLocation(cdataContentStart) });
    }

    // After the CDATA content, the XML wrapper resumes at ']]>'
    xmlStart = cdataClose; // ']]>' is part of the XML wrapper
    pos = cdataClose + CDATA_CLOSE.length;
  }

  // Final XML wrapper region: from the last ']]>' to the end of the file
  if (xmlStart < text.length) {
    result.push({ start: posToLocation(xmlStart), end: posToLocation(text.length) });
  }

  return result;
}



/**
 * Extract ST source from a TwinCAT file.
 *
 * @param content   The raw file content (UTF-8 text).
 * @param ext       The file extension, e.g. `.TcPOU` or `.st`.
 *                  Case-insensitive; the leading dot is required.
 * @returns         An ExtractionResult with the extracted source and line map.
 */
export function extractST(content: string, ext: string): ExtractionResult {
  const normalised = ext.toLowerCase();

  // Plain ST files pass through untouched.
  if (!XML_EXTENSIONS.has(normalised)) {
    if (content === '') {
      return { source: '', lineMap: [], sections: [], passthrough: true };
    }
    const lines = content.split('\n');
    return {
      source: content,
      lineMap: lines.map((_, i) => i),
      sections: [],
      passthrough: true,
    };
  }

  const cdatas = extractTopLevelCDATAs(content);
  return buildResult(cdatas);
}

// ---------------------------------------------------------------------------
// Compatibility exports (for projectReader.ts)
// ---------------------------------------------------------------------------

/**
 * Mapping from extracted code line (0-based) to original source line (0-based).
 */
export type OffsetMap = Record<number, number>;

/**
 * Extract ST code from a TwinCAT source file, returning a legacy-compatible
 * result shape used by projectReader.ts.
 *
 * Prefer `extractST` for new code.
 */
export function extractStFromTwinCAT(
  filePath: string,
  fileContent: string,
): { stCode: string; offsets: OffsetMap } {
  const ext = path.extname(filePath);
  const result = extractST(fileContent, ext);
  const offsets: OffsetMap = {};
  result.lineMap.forEach((originalLine, extractedLine) => {
    offsets[extractedLine] = originalLine;
  });
  return { stCode: result.source, offsets };
}
